apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: {{ .Values.operatorGroupName }}
  namespace: {{ .Values.operatorNamespace }}
spec:
  targetNamespaces:
  - {{ .Values.tackleNamespace }}