apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.operatorGroupName }}
  namespace: {{ .Values.operatorNamespace }}
spec:
  targetNamespaces:
  - {{ .Values.tackleNamespace }}