apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mta-operator
  namespace: mta-poc
spec:
  channel: stable-v7.2
  installPlanApproval: Automatic
  name: mta-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: mta-operator.v7.2.2